### PR TITLE
Fix TextTruncate props after npm update and types update

### PR DESCRIPTION
**Pull request by dgading**
I was having trouble building on Ubuntu from a missing `lightningcss` package. Running `npm update` seems to have fixed the issue for builds completing.

### CODE REVIEW

**Review by brdunfield — COMMENTED** [review]
It looks like we get a different text truncate error now..

```
 textElement={dangerousDescriptionElement}
      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ No overload matches this call.
    Overload 1 of 2, '(props: TextTruncateProps | Readonly<TextTruncateProps>): TextTruncate', gave the following error.
      Type '({ children }: { children: string; }) => JSX.Element' is not assignable to type 'ReactNode'.
    Overload 2 of 2, '(props: TextTruncateProps, context: any): TextTruncate', gave the following error.
      Type '({ children }: { children: string; }) => JSX.Element' is not assignable to type 'ReactNode'.```

**Comment by dgading** [comment]
Ok I'll see if I can fix that, it looks like a real issue. The one I was seeing was just typescrip complaining there was no types declaration of that library

**Comment by dgading** [comment]
This PR has grown a little from the original task, but does the following:

- Adds types for React Text Truncate
- Fixes the type error in the above, but finding the first html element in a SearchListItem description and passes that to the React Text Truncate component, instead of a dangerouslySetInnerHTML span.
- Adds an id to each SearchListItem's update date and aria-describedby to the h2 link with that id
- Moves the key from the SearchListItem to the DatasetSearch map function and adds a key to the test data to clear a console.log from Jest tests

**Comment by brdunfield** [comment]
Adding my notes as comments as this PR spans multiple tickets:

WCMS-19595: aria-described by and date span confirmed locally as per ticket testing steps

**Comment by brdunfield** [comment]
My workspaced instance is showing a typescript warning, but the non-workspaced one does not. I am guessing there is some weirdness with the installing and the workspace.

**Review by brdunfield — APPROVED** [review]
LGTM!

**Pull request merged**
