### PR TITLE
2.x styles fix

### PR DESCRIPTION
**Pull request by dgading**
With Parcel if each component imports its own scss file, we get a css file as an output. I've also combined the Headers into one component that just needs a min/max instead of making each site write that extra code and complicate the Layout component.

### CODE REVIEW

**Review by brdunfield — COMMENTED** [review]
A couple things:
Screen Shot 2023-03-01 at 10 25 37 AM
The search button in the top nav still needs a bit of work.

Screen Shot 2023-03-01 at 10 25 40 AM
The clear all filters button looks like it needs some padding as well. However I notice this button looks completely different in prod. Is this another case of styles overriding in prod that I don't see locally?

**Review by brdunfield — COMMENTED** [review]
localhost_3000_datasets_page=4(iPhone 12 Pro)
It looks like the Mobile header is not visible at the moment

**Comment by brdunfield** [comment]
localhost_3000_datasets_page=4(iPhone 12 Pro)
Here's what the mobile header looks like when also running the downstream PFS branch

**Review by brdunfield — COMMENTED** [review]
The search modal also looks significantly different to what's on prod, and lacks the "close" button in the top right of the screen.

**Comment by dgading** [comment]
I think for this PR I expect a lot of the stuff is still broken. My goal was mostly to get css compiling for the used components/templates and fix an error in the build process from the lack of Sass variables. I didn't touch anything with the modal and I didn't touch many of the new prop changes introduced in the 6.x branch.

**Review by brdunfield — APPROVED** [review]
In that case LGTM. I'm not seeing any build errors running this and the updated downstream on my local, and it seems like the CSS files are being picked up!

**Pull request merged**
